# Generated by Django 4.1.6 on 2023-02-03 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_authcode_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="authcode_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1969, 12, 31, 15, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
